# Copyright 2019 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "sawtooth"
version = "0.6.6"
authors = ["Cargill Incorporated"]
edition = "2018"
license = "Apache-2.0"
description = """\
    Hyperledger Sawtooth is an enterprise blockchain platform for building \
    distributed ledger applications and networks.
"""

[dependencies]
base64 = { version = "0.13", optional = true }
cbor-codec = { version = "0.7", optional = true }
cylinder = "0.2"
diesel = { version = "1.0", features = ["r2d2", "serde_json"], optional = true }
diesel_migrations = { version = "1.4", optional = true }
hex = "0.4"
log = "0.4"
lmdb-zero = { version = "0.4", optional = true }
metrics = { version = "0.12", features = ["std"], optional = true }
openssl = { version = "0.10", optional = true }
protobuf = "2.23"
redis = { version = "0.20", default-features = false, optional = true }
reqwest = { version = "0.11", optional = true, features = ["blocking", "json"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
transact = "0.3"
uluru = { version = "0.4", optional = true }

[dev-dependencies]
rand = "0.8"

[build-dependencies]
protoc-rust = "2.0"
glob = "0.3"

[features]
default = []

stable = []

experimental = [
    # The experimental feature extends stable:
    "stable",
    # The following features are experimental:
    "btree-store",
    "client",
    "client-rest",
    "lmdb-store",
    "pending-batch-queue",
    "postgres",
    "receipt-store",
    "redis-store",
    "sqlite",
    "stores",
    "transaction-receipt-store",
    "transaction-receipt-store-lmdb",
    "validator-internals",
]

btree-store = ["stores"]
client = []
client-rest = ["base64", "client", "reqwest", "serde"]
lmdb-store = ["lmdb-zero", "stores"]
pending-batch-queue = ["validator-internals"]
postgres = ["diesel_migrations", "transaction-receipt-store"]
receipt-store = ["stores"]
redis-store = ["redis", "stores"]
sqlite = ["diesel/sqlite", "diesel_migrations", "transaction-receipt-store"]
stores = []
transaction-receipt-store = []
transaction-receipt-store-lmdb = ["lmdb-zero", "transaction-receipt-store"]
validator-internals = [
  "cbor-codec",
  "lmdb-zero",
  "metrics",
  "openssl",
  "uluru",
]
